# Only build on tags
if: tag IS present

jobs:
    include:
        - stage: build
          os: osx
          language: shell
          script:
              - './travis/build-macos.sh'

        - stage: build
          os: linux
          dist: xenial
          language: python
          python:
              - '3.7'
          script:
              - ./travis/build-linux.sh

        - stage: build
          os: windows
          language: shell
          script:
              - ./travis/build-win.sh

        - stage: Deploy
              - ./travis/complete.sh
