# Only build on tags
if: tag IS present

jobs:
    include:
        - stage: build
          os: osx
          language: shell
          script:
              - './travis/build-macos.sh'

        - stage: build
          os: linux
          dist: xenial
          language: python
          python:
              - '3.7'
          before_install:
              - sudo apt update
              - sudo apt install libusb-1.0-0-dev libudev-dev
          script:
              - ./travis/build-linux.sh
          deploy:
              provider: releases
              api_key: $GITHUB_TOKEN
              file: './dist/guardiandeck-linux'
              skip_cleanup: true

        - stage: build
          os: windows
          language: shell
          script:
              - ./travis/build-win.sh
